### ISSUE TITLE
J19 and J17 Umbilical Connectors

### ISSUE THREAD

**Issue by Basilhs-Moustakas** [PeakSat/OBCBoard_PCB#1]
We need to remove J19 connector and instead make J17 26 pin with the following pinout:

 Pinout for J17 ([M80-6662622](https://gr.mouser.com/ProductDetail/Harwin/M80-6662622?qs=IQR8xM2KsGhXAWHQWi6yag%3D%3D)):

+ OBC SWDIO
+ OBC SWCLK
+ ADCS_UART_TX
+ ADCS_UART_RX
+ CAN1+
+ CAN1-
+ OBC RST
+ OBC 3V3 REF
+ GND
+ ADCS SWDIO
+ ADCS SWCLK
+ OBC_UART_RX
+ OBC_UART_TX
+ CAN2+
+ CAN2-
+ ADCS_RESET
+ GND
+ COMMS VREF 3V3
+ COMMS SWDIO
+ COMMS SWCLK
+ COMMS RESET
+ COMMS UART RX
+ COMMS UART TX

The COMMS signals also need to be added on the PC104

**Comment by giatats** [comment]
Done

**Comment by Basilhs-Moustakas** [comment]
OK but you should now remove the J19 connector
