### ISSUE TITLE
Payload Connector

### ISSUE THREAD

**Issue by Basilhs-Moustakas** [PeakSat/OBCBoard_PCB#2]
Power supply and CAN should be removed from Payload connector. Also we should add a direct connection with PPS

![image](https://github.com/PeakSat/OBCBoard_PCB/assets/48751090/611a3e91-6fd4-49b4-880a-942c7bd4237b)

**Comment by giatats** [comment]
Change tthe connector to 4-pin Molex? 
RS422_A, RS422_B, GND, PPS

**Comment by Basilhs-Moustakas** [comment]
Yes it will help save valuable space. We can do 6 pin if 2 differential pairs are needed.
