### ISSUE TITLE
RS-422 interface

### ISSUE THREAD

**Issue by Basilhs-Moustakas** [PeakSat/OBCBoard_PCB#3]
I think RS-422 is a bit sus. For some reason the payload has 2 differential pairs for the RS-422 interface while the ADM3483 has indeed 2 connections for both input and output. Perhaps they are using the ADM3488 version and I was wrong? I think we need to clarify with them.

![image](https://github.com/PeakSat/OBCBoard_PCB/assets/48751090/c8bed335-9cbc-46e3-af95-4c45daa7d7e1)

![image](https://github.com/PeakSat/OBCBoard_PCB/assets/48751090/566ddeb0-94ce-4beb-8cca-79615182c200)

**Comment by giatats** [comment]
Mail to Astrolight for clarification.

**Comment by Basilhs-Moustakas** [comment]
@giatats I think we also need termination resistor somewhere. Typically the circuit looks like this which, however Astrolight specifies that they only place termination resistor on A-B end... I think we should do the same.

![image](https://github.com/PeakSat/OBCBoard_PCB/assets/48751090/5ab67426-79be-40ef-b3cb-4e2520109a62)


![image](https://github.com/PeakSat/OBCBoard_PCB/assets/48751090/bf5754fb-5948-4ea2-8df0-f010bc1d3ba1)

**Comment by Basilhs-Moustakas** [comment]
ok so there is an RS-422 impementation guide from analog circuits. Here we can see this:

![image](https://github.com/PeakSat/OBCBoard_PCB/assets/48751090/26a4c330-32d4-4744-9489-bf0468085121)

So from what I understand we need to place an 120Ohm termination resistor on our Z-Y end an then have a 60Ohm impedance cable to connect to the terminal
