### ISSUE TITLE
GND Vias Placement

### ISSUE THREAD

**Issue by Basilhs-Moustakas** [PeakSat/OBCBoard_PCB#5]
The power plane in this area is almost cut in half by these four vias. Furthermore one of the vias are placed almost on top of the pad which can lead to assembly issues. Is it possible to fine tune their position?

![image](https://github.com/PeakSat/OBCBoard_PCB/assets/48751090/120a5a61-fa51-4223-873f-de11d1a7e98f)

**Comment by giatats** [comment]
moved vias around
