### ISSUE TITLE
CAN differential pair

### ISSUE THREAD

**Issue by Basilhs-Moustakas** [PeakSat/OBCBoard_PCB#7]
For a small part of the track length there is no impedance control for both CAN bus channels. I mean in nominal conditions this might not be a problem but with the long TVAC cables and extreme temperature you dont want to risk it. Match the tracks length as well.

![image](https://github.com/PeakSat/OBCBoard_PCB/assets/48751090/6e394c40-4c9e-4c56-9a3d-d91cf14cc6fc)

**Comment by Basilhs-Moustakas** [comment]
Length tuning is fine but you also need to route them as differantial pairs for the channel to have a proper characteristic impedance

**Comment by giatats** [comment]
Done
