### ISSUE TITLE
[Minor] 90 degree angle on track

### ISSUE THREAD

**Issue by Basilhs-Moustakas** [PeakSat/OBCBoard_PCB#8]
90 degree angles are bad for 2 reasons:

1. They can cause EMC problems in high-speed signals
2. They make your PCB ugly 

Try to avoid them

![image](https://github.com/PeakSat/OBCBoard_PCB/assets/48751090/063d78e4-b3c4-45df-995e-8bc683230dc7)

**Comment by giatats** [comment]
Twra to board einai panemorfo
