### ISSUE TITLE
ADM 5V

### ISSUE THREAD

**Issue by Basilhs-Moustakas** [PeakSat/OBCBoard_PCB#9]
We expect up to 2A in the EPS_5V_ADM track. 0.3mm is definetely not sufficient. Try to have a dedicated power filled zone in a different layer or make it at least 1.5mm wide. Use the track width calculator tool to measure voltage drop. Anything above 0.05V should not be acceptable.

![image](https://github.com/PeakSat/OBCBoard_PCB/assets/48751090/acca0aeb-8a11-43bf-b366-7533c3001636)

**Comment by Basilhs-Moustakas** [comment]
GND shall also have a thick track and probably multiple vias as well. For the number of vias needed you can also use the calculator tool of kicad

**Comment by Basilhs-Moustakas** [comment]
Cool but whats stopping us from making it bigger like this? Also why this no copper zone on the left?

![image](https://github.com/PeakSat/OBCBoard_PCB/assets/48751090/5e0a17c5-8508-4901-8db0-81f1e9dec54e)


![image](https://github.com/PeakSat/OBCBoard_PCB/assets/48751090/438efc80-0ed7-4c8c-8541-6c95a51d625d)

**Comment by giatats** [comment]
Re-arranged power planes
